.TH "BUS< BUSWIDTH, DATA_WIDTH >::address" 3 "Version v1.0" "SoCPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BUS< BUSWIDTH, DATA_WIDTH >::address
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBaddr\fP"
.br
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<unsigned int BUSWIDTH = 32, \fBDATAWIDTH\fP DATA_WIDTH = D8BIT> unsigned int addr"

.SS "template<unsigned int BUSWIDTH = 32, \fBDATAWIDTH\fP DATA_WIDTH = D8BIT> unsigned int id"

.SS "template<unsigned int BUSWIDTH = 32, \fBDATAWIDTH\fP DATA_WIDTH = D8BIT> unsigned int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for SoCPlatform from the source code\&.
