.TH "DummyMaster< BUSWIDTH >::localdata" 3 "Version v1.0" "SoCPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyMaster< BUSWIDTH >::localdata
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBm_data\fP"
.br
.ti -1c
.RI "unsigned int \fBm_length\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<unsigned int BUSWIDTH = 32> unsigned char* m_data"

.PP
Referenced by \fBDummyMaster< BUSWIDTH >::get_received_32bit_data()\fP, \fBDummyMaster< BUSWIDTH >::get_received_data()\fP, and \fBDummyMaster< BUSWIDTH >::nb_transport_bw()\fP\&.
.SS "template<unsigned int BUSWIDTH = 32> unsigned int m_length"


.SH "Author"
.PP 
Generated automatically by Doxygen for SoCPlatform from the source code\&.
