.TH "common/DummyMaster.h" 3 "Version v1.0" "SoCPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/DummyMaster.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc>\fP
.br
\fR#include <tlm>\fP
.br
\fR#include <tlm_utils/simple_initiator_socket\&.h>\fP
.br
\fR#include <tlm_utils/simple_target_socket\&.h>\fP
.br
\fR#include <tlm_utils/multi_passthrough_initiator_socket\&.h>\fP
.br
\fR#include <tlm_utils/multi_passthrough_target_socket\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include 'Registerif\&.h'\fP
.br
\fR#include 'bus\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDummyMaster< BUSWIDTH >\fP"
.br
.ti -1c
.RI "struct \fBDummyMaster< BUSWIDTH >::localdata\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SoCPlatform from the source code\&.
