.TH "common/Inverter.h" 3 "Version v1.0" "SoCPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/Inverter.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_MODULE\fP (Inverter)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SC_MODULE (Inverter )"

.SH "Author"
.PP 
Generated automatically by Doxygen for SoCPlatform from the source code\&.
