.TH "common/Registerif.h" 3 "Version v1.0" "SoCPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/Registerif.h
.SH SYNOPSIS
.br
.PP
\fR#include <unordered_map>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegister\fP"
.br
.ti -1c
.RI "class \fBRegisterInterface\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBREGPERMISSION\fP { \fBREADWRITE\fP = 0, \fBREADONLY\fP = 1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBREGPERMISSION\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIREADWRITE \fP\fP
.TP
\fB\fIREADONLY \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for SoCPlatform from the source code\&.
