wrapper_four_bit_adder< BUSWIDTH >
#include "Adder_wrapper.h"
Inherits sc_module.
Public Member Functions
 wrapper_four_bit_adder (sc_core::sc_module_name name, bool message=false)
Public Attributes
tlm_utils::simple_target_socket< wrapper_four_bit_adder, BUSWIDTH > target_socket
Private Member Functions
void binding_inout ()
void cb_ADDERINPUT (const std::string &name, uint32_t value, uint32_t old_value, uint32_t mask, uint32_t ch)
void init_register ()
tlm::tlm_sync_enum nb_transport_fw (tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_core::sc_time &delay)
void output_handling ()
Private Attributes
sc_signal< sc_uint< 4 > > a
sc_signal< sc_uint< 4 > > b
sc_signal< bool > cin
sc_signal< bool > cout
four_bit_adder m_four_bit_adder
bool m_message
std::string m_name
RegisterInterface regs
sc_signal< sc_uint< 4 > > sum
Constructor & Destructor Documentation
wrapper_four_bit_adder()
template<unsigned int BUSWIDTH = 32>
 wrapper_four_bit_adder (sc_core::sc_module_name name, bool message = false) [inline]
References wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), wrapper_four_bit_adder< BUSWIDTH >::cout, wrapper_four_bit_adder< BUSWIDTH >::init_register(), wrapper_four_bit_adder< BUSWIDTH >::nb_transport_fw(), wrapper_four_bit_adder< BUSWIDTH >::output_handling(), wrapper_four_bit_adder< BUSWIDTH >::sum, and wrapper_four_bit_adder< BUSWIDTH >::target_socket.
Member Function Documentation
binding_inout()
template<unsigned int BUSWIDTH = 32>
void binding_inout () [inline], [private]
References wrapper_four_bit_adder< BUSWIDTH >::a, wrapper_four_bit_adder< BUSWIDTH >::b, wrapper_four_bit_adder< BUSWIDTH >::cin, wrapper_four_bit_adder< BUSWIDTH >::cout, wrapper_four_bit_adder< BUSWIDTH >::m_four_bit_adder, and wrapper_four_bit_adder< BUSWIDTH >::sum.
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder().
cb_ADDERINPUT()
template<unsigned int BUSWIDTH = 32>
void cb_ADDERINPUT (const std::string & name, uint32_t value, uint32_t old_value, uint32_t mask, uint32_t ch) [inline], [private]
References wrapper_four_bit_adder< BUSWIDTH >::a, wrapper_four_bit_adder< BUSWIDTH >::b, and wrapper_four_bit_adder< BUSWIDTH >::cin.
Referenced by wrapper_four_bit_adder< BUSWIDTH >::init_register().
init_register()
template<unsigned int BUSWIDTH = 32>
void init_register () [inline], [private]
References ADDERINPUT, ADDEROUTPUT, wrapper_four_bit_adder< BUSWIDTH >::cb_ADDERINPUT(), and wrapper_four_bit_adder< BUSWIDTH >::regs.
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder().
nb_transport_fw()
template<unsigned int BUSWIDTH = 32>
tlm::tlm_sync_enum nb_transport_fw (tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_core::sc_time & delay) [inline], [private]
References wrapper_four_bit_adder< BUSWIDTH >::m_message, wrapper_four_bit_adder< BUSWIDTH >::m_name, wrapper_four_bit_adder< BUSWIDTH >::regs, and wrapper_four_bit_adder< BUSWIDTH >::target_socket.
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder().
output_handling()
template<unsigned int BUSWIDTH = 32>
void output_handling () [inline], [private]
References ADDEROUTPUT, wrapper_four_bit_adder< BUSWIDTH >::cout, wrapper_four_bit_adder< BUSWIDTH >::regs, and wrapper_four_bit_adder< BUSWIDTH >::sum.
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder().
Member Data Documentation
a
template<unsigned int BUSWIDTH = 32>
sc_signal<sc_uint<4> > a [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), and wrapper_four_bit_adder< BUSWIDTH >::cb_ADDERINPUT().
b
template<unsigned int BUSWIDTH = 32>
sc_signal<sc_uint<4> > b [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), and wrapper_four_bit_adder< BUSWIDTH >::cb_ADDERINPUT().
cin
template<unsigned int BUSWIDTH = 32>
sc_signal<bool> cin [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), and wrapper_four_bit_adder< BUSWIDTH >::cb_ADDERINPUT().
cout
template<unsigned int BUSWIDTH = 32>
sc_signal<bool> cout [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder(), wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), and wrapper_four_bit_adder< BUSWIDTH >::output_handling().
m_four_bit_adder
template<unsigned int BUSWIDTH = 32>
four_bit_adder m_four_bit_adder [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::binding_inout().
m_message
template<unsigned int BUSWIDTH = 32>
bool m_message [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::nb_transport_fw().
m_name
template<unsigned int BUSWIDTH = 32>
std::string m_name [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::nb_transport_fw().
regs
template<unsigned int BUSWIDTH = 32>
RegisterInterface regs [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::init_register(), wrapper_four_bit_adder< BUSWIDTH >::nb_transport_fw(), and wrapper_four_bit_adder< BUSWIDTH >::output_handling().
sum
template<unsigned int BUSWIDTH = 32>
sc_signal<sc_uint<4> > sum [private]
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder(), wrapper_four_bit_adder< BUSWIDTH >::binding_inout(), and wrapper_four_bit_adder< BUSWIDTH >::output_handling().
target_socket
template<unsigned int BUSWIDTH = 32>
tlm_utils::simple_target_socket< wrapper_four_bit_adder, BUSWIDTH> target_socket
Referenced by wrapper_four_bit_adder< BUSWIDTH >::wrapper_four_bit_adder(), and wrapper_four_bit_adder< BUSWIDTH >::nb_transport_fw().
The documentation for this class was generated from the following file:
models/Adder/ Adder_wrapper.h