DummySlave< BUSWIDTH >
#include "DummySlave.h"
Public Member Functions
 DummySlave (sc_core::sc_module_name name, bool message=false)
DummySlave.
sc_core::sc_in< bool > * add_input_port (const std::string &name)
add_input_port
sc_core::sc_out< bool > * add_output_port (const std::string &name)
add_output_port
void enable_monitor_clock (bool is_enable)
enable_monitor_clock
void monitor_ports (bool is_enable)
monitor_ports
bool read_input_ports (const std::string &name)
read_input_ports
void set_output_ports (const std::string &name, bool value)
set_output_ports
void trigger_output_ports (const std::string &name, bool high_level, bool is_pos)
set_output_ports
Public Attributes
sc_core::sc_in< bool > clk
sc_core::sc_in< bool > rst
tlm_utils::simple_target_socket< DummySlave, BUSWIDTH > target_socket
Private Member Functions
void cb_DUMMYRESULT (const std::string &name, uint32_t value, uint32_t old_value, uint32_t mask, uint32_t ch)
cb_DUMMYRESULT
void end_of_elaboration () override
end_of_elaboration
void init_registers ()
init_registers
void monitor_inputs ()
monitor_inputs
void mth_reset ()
mth_reset
void mth_synchronize_cycles ()
mth_synchronize_cycles
tlm::tlm_sync_enum nb_transport_fw (tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_core::sc_time &delay)
nb_transport_fw
void thr_triggered_port_process ()
thr_triggered_port_process
Private Attributes
sc_core::sc_event e_triggerd_port
std::map< std::string, sc_core::sc_in< bool > * > input_ports
std::map< std::string, bool > input_val_ports
bool m_clkmonitor
bool m_cur_is_pos
std::string m_cur_port_name
bool m_cur_triggered_val
bool m_message
std::string m_name
bool m_portmonitor
std::map< std::string, sc_core::sc_out< bool > * > output_ports
std::map< std::string, bool > output_val_ports
 RegisterInterface regs
Constructor & Destructor Documentation
DummySlave()
template<unsigned int BUSWIDTH = 32>
 DummySlave (sc_core::sc_module_name name, bool message = false) [inline]
DummySlave.
DummySlave Constructure
Parameters
name Reference to sc_module name
message To enable message log
References DummySlave< BUSWIDTH >::clk, DummySlave< BUSWIDTH >::e_triggerd_port, DummySlave< BUSWIDTH >::init_registers(), DummySlave< BUSWIDTH >::mth_reset(), DummySlave< BUSWIDTH >::mth_synchronize_cycles(), DummySlave< BUSWIDTH >::nb_transport_fw(), DummySlave< BUSWIDTH >::rst, DummySlave< BUSWIDTH >::target_socket, and DummySlave< BUSWIDTH >::thr_triggered_port_process().
Member Function Documentation
add_input_port()
template<unsigned int BUSWIDTH = 32>
sc_core::sc_in< bool > * add_input_port (const std::string & name) [inline]
add_input_port
To add input specific input ports to DummySlave
Parameters
name Reference to the port name
References DummySlave< BUSWIDTH >::input_ports, and DummySlave< BUSWIDTH >::input_val_ports.
add_output_port()
template<unsigned int BUSWIDTH = 32>
sc_core::sc_out< bool > * add_output_port (const std::string & name) [inline]
add_output_port
To add ouput specific output ports to DummySlave
Parameters
name Reference to the port name
References DummySlave< BUSWIDTH >::output_ports, and DummySlave< BUSWIDTH >::output_val_ports.
cb_DUMMYRESULT()
template<unsigned int BUSWIDTH = 32>
void cb_DUMMYRESULT (const std::string & name, uint32_t value, uint32_t old_value, uint32_t mask, uint32_t ch) [inline], [private]
cb_DUMMYRESULT
The callback function for DUMMYRESULT register
Parameters
name The name of register
value The value of register
old_value the previous value
mask the mask of register
ch the register channel
Referenced by DummySlave< BUSWIDTH >::init_registers().
enable_monitor_clock()
template<unsigned int BUSWIDTH = 32>
void enable_monitor_clock (bool is_enable) [inline]
enable_monitor_clock
Using to enable or disable clock monitor operation
Parameters
is_enable Indicating whether enabling or disabling clock monitor
References DummySlave< BUSWIDTH >::m_clkmonitor.
end_of_elaboration()
template<unsigned int BUSWIDTH = 32>
void end_of_elaboration () [inline], [override], [private]
end_of_elaboration
The function end_of_elaboration is called before starting simulation
References DummySlave< BUSWIDTH >::input_ports, and DummySlave< BUSWIDTH >::monitor_inputs().
init_registers()
template<unsigned int BUSWIDTH = 32>
void init_registers () [inline], [private]
init_registers
Initialization registers
References RegisterInterface::add_register(), DummySlave< BUSWIDTH >::cb_DUMMYRESULT(), DUMMYRESULT, READWRITE, DummySlave< BUSWIDTH >::regs, and RegisterInterface::set_register_callback().
Referenced by DummySlave< BUSWIDTH >::DummySlave().
monitor_inputs()
template<unsigned int BUSWIDTH = 32>
void monitor_inputs () [inline], [private]
monitor_inputs
The method uses to monitor input ports
References DummySlave< BUSWIDTH >::input_ports, DummySlave< BUSWIDTH >::input_val_ports, DummySlave< BUSWIDTH >::m_name, and DummySlave< BUSWIDTH >::m_portmonitor.
Referenced by DummySlave< BUSWIDTH >::end_of_elaboration().
monitor_ports()
template<unsigned int BUSWIDTH = 32>
void monitor_ports (bool is_enable) [inline]
monitor_ports
Using to enable or disable port monitor operation
Parameters
is_enable Indicating whether enabling or disabling port monitor
References DummySlave< BUSWIDTH >::m_portmonitor.
mth_reset()
template<unsigned int BUSWIDTH = 32>
void mth_reset () [inline], [private]
mth_reset
Implementation the method to handle reset operation
References DummySlave< BUSWIDTH >::regs, and RegisterInterface::reset_regs().
Referenced by DummySlave< BUSWIDTH >::DummySlave().
mth_synchronize_cycles()
template<unsigned int BUSWIDTH = 32>
void mth_synchronize_cycles () [inline], [private]
mth_synchronize_cycles
Implementation the method to monitor clock cycles
References DummySlave< BUSWIDTH >::m_clkmonitor.
Referenced by DummySlave< BUSWIDTH >::DummySlave().
nb_transport_fw()
template<unsigned int BUSWIDTH = 32>
tlm::tlm_sync_enum nb_transport_fw (tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_core::sc_time & delay) [inline], [private]
nb_transport_fw
Implements the non-blocking backward transport interface for the initiator.
Parameters
trans Reference to the generic payload object containing the transaction details such as command, address, and data.
phase Reference to the transaction phase. The current phase of the transaction, which may be updated by the function.
delay Reference to the annotated delay. Specifies the timing delay for the transaction and may be updated by the function.
Returns
tlm::tlm_sync_enum Enumeration indicating the synchronization state of the transaction:
TLM_ACCEPTED: Transaction is accepted, and no immediate further action is required.
TLM_UPDATED: Transaction phase has been updated. The initiator should check the new phase.
TLM_COMPLETED: Transaction is completed immediately, and no further phases will occur.
References DummySlave< BUSWIDTH >::m_message, DummySlave< BUSWIDTH >::m_name, DummySlave< BUSWIDTH >::regs, DummySlave< BUSWIDTH >::target_socket, and RegisterInterface::update_register().
Referenced by DummySlave< BUSWIDTH >::DummySlave().
read_input_ports()
template<unsigned int BUSWIDTH = 32>
bool read_input_ports (const std::string & name) [inline]
read_input_ports
Using to read the value of specific port
Parameters
name Reference to the port name
References DummySlave< BUSWIDTH >::input_ports.
set_output_ports()
template<unsigned int BUSWIDTH = 32>
void set_output_ports (const std::string & name, bool value) [inline]
set_output_ports
Using to set specific output port
Parameters
name Reference to the port name
value the value of the output port
References DummySlave< BUSWIDTH >::output_ports.
thr_triggered_port_process()
template<unsigned int BUSWIDTH = 32>
void thr_triggered_port_process () [inline], [private]
thr_triggered_port_process
Implementation the process to trigger specific ports
References DummySlave< BUSWIDTH >::clk, DummySlave< BUSWIDTH >::e_triggerd_port, DummySlave< BUSWIDTH >::m_cur_is_pos, DummySlave< BUSWIDTH >::m_cur_port_name, DummySlave< BUSWIDTH >::m_cur_triggered_val, and DummySlave< BUSWIDTH >::output_ports.
Referenced by DummySlave< BUSWIDTH >::DummySlave().
trigger_output_ports()
template<unsigned int BUSWIDTH = 32>
void trigger_output_ports (const std::string & name, bool high_level, bool is_pos) [inline]
set_output_ports
Using to trigger specific output port
Parameters
name Reference to the port name
high_level Indicating the triggered level
is_pos Indicating the clock edge synchronization is positive or negative
References DummySlave< BUSWIDTH >::m_cur_is_pos, DummySlave< BUSWIDTH >::m_cur_port_name, DummySlave< BUSWIDTH >::m_cur_triggered_val, and DummySlave< BUSWIDTH >::output_ports.
Member Data Documentation
clk
template<unsigned int BUSWIDTH = 32>
sc_core::sc_in<bool> clk
Referenced by DummySlave< BUSWIDTH >::DummySlave(), and DummySlave< BUSWIDTH >::thr_triggered_port_process().
e_triggerd_port
template<unsigned int BUSWIDTH = 32>
sc_core::sc_event e_triggerd_port [private]
Referenced by DummySlave< BUSWIDTH >::DummySlave(), and DummySlave< BUSWIDTH >::thr_triggered_port_process().
input_ports
template<unsigned int BUSWIDTH = 32>
std::map<std::string, sc_core::sc_in<bool>*> input_ports [private]
Referenced by DummySlave< BUSWIDTH >::add_input_port(), DummySlave< BUSWIDTH >::end_of_elaboration(), DummySlave< BUSWIDTH >::monitor_inputs(), and DummySlave< BUSWIDTH >::read_input_ports().
input_val_ports
template<unsigned int BUSWIDTH = 32>
std::map<std::string, bool> input_val_ports [private]
Referenced by DummySlave< BUSWIDTH >::add_input_port(), and DummySlave< BUSWIDTH >::monitor_inputs().
m_clkmonitor
template<unsigned int BUSWIDTH = 32>
bool m_clkmonitor [private]
Referenced by DummySlave< BUSWIDTH >::enable_monitor_clock(), and DummySlave< BUSWIDTH >::mth_synchronize_cycles().
m_cur_is_pos
template<unsigned int BUSWIDTH = 32>
bool m_cur_is_pos [private]
Referenced by DummySlave< BUSWIDTH >::thr_triggered_port_process(), and DummySlave< BUSWIDTH >::trigger_output_ports().
m_cur_port_name
template<unsigned int BUSWIDTH = 32>
std::string m_cur_port_name [private]
Referenced by DummySlave< BUSWIDTH >::thr_triggered_port_process(), and DummySlave< BUSWIDTH >::trigger_output_ports().
m_cur_triggered_val
template<unsigned int BUSWIDTH = 32>
bool m_cur_triggered_val [private]
Referenced by DummySlave< BUSWIDTH >::thr_triggered_port_process(), and DummySlave< BUSWIDTH >::trigger_output_ports().
m_message
template<unsigned int BUSWIDTH = 32>
bool m_message [private]
Referenced by DummySlave< BUSWIDTH >::nb_transport_fw().
m_name
template<unsigned int BUSWIDTH = 32>
std::string m_name [private]
Referenced by DummySlave< BUSWIDTH >::monitor_inputs(), and DummySlave< BUSWIDTH >::nb_transport_fw().
m_portmonitor
template<unsigned int BUSWIDTH = 32>
bool m_portmonitor [private]
Referenced by DummySlave< BUSWIDTH >::monitor_inputs(), and DummySlave< BUSWIDTH >::monitor_ports().
output_ports
template<unsigned int BUSWIDTH = 32>
std::map<std::string, sc_core::sc_out<bool>*> output_ports [private]
Referenced by DummySlave< BUSWIDTH >::add_output_port(), DummySlave< BUSWIDTH >::set_output_ports(), DummySlave< BUSWIDTH >::thr_triggered_port_process(), and DummySlave< BUSWIDTH >::trigger_output_ports().
output_val_ports
template<unsigned int BUSWIDTH = 32>
std::map<std::string, bool> output_val_ports [private]
Referenced by DummySlave< BUSWIDTH >::add_output_port().
regs
template<unsigned int BUSWIDTH = 32>
 RegisterInterface regs [private]
Referenced by DummySlave< BUSWIDTH >::init_registers(), DummySlave< BUSWIDTH >::mth_reset(), and DummySlave< BUSWIDTH >::nb_transport_fw().
rst
template<unsigned int BUSWIDTH = 32>
sc_core::sc_in<bool> rst
Referenced by DummySlave< BUSWIDTH >::DummySlave().
target_socket
template<unsigned int BUSWIDTH = 32>
tlm_utils::simple_target_socket< DummySlave, BUSWIDTH> target_socket
Referenced by DummySlave< BUSWIDTH >::DummySlave(), and DummySlave< BUSWIDTH >::nb_transport_fw().
The documentation for this class was generated from the following file:
common/ DummySlave.h