RegisterInterface
#include "Registerif.h"
Public Member Functions
void add_register (std::string name, uint64_t address, uint32_t init, uint32_t mask, uint32_t ch, REGPERMISSION permission)
add_register
void dump_registers ()
update_register Using to show all register informations
 Register & operator[] (std::string name)
add_register The operator to get register by name for example this->reg[name]
 Register & operator[] (uint64_t address)
operator[] The operator to get register by address for example this->reg[addr]
void reset_regs ()
update_register Using to reset registers
void set_register_callback (const std::string &name, Register::Callback cb)
update_register Using to register register callback function
void update_register (uint64_t address, uint32_t value)
update_register Using to update the value of register with specific address
Private Attributes
std::map< std::string, Register > registers
Member Function Documentation
add_register()
void add_register (std::string name, uint64_t address, uint32_t init, uint32_t mask, uint32_t ch, REGPERMISSION permission) [inline]
add_register
Constructure
Parameters
name The register name
address The register base address
init The register initialization value
mask The register mask
ch The register channel
permission Indicating this register is read /write or read only permission
References registers.
Referenced by DMAC< BUSWIDTH >::init_registers(), and DummySlave< BUSWIDTH >::init_registers().
dump_registers()
void dump_registers () [inline]
update_register Using to show all register informations
References registers.
operator[]() [1/2]
 Register & operator[] (std::string name) [inline]
add_register The operator to get register by name for example this->reg[name]
Parameters
name The register name
Returns
Register object with corresponding name
References registers.
operator[]() [2/2]
 Register & operator[] (uint64_t address) [inline]
operator[] The operator to get register by address for example this->reg[addr]
Parameters
address The register address
Returns
Register object with corresponding address
References registers.
reset_regs()
void reset_regs () [inline]
update_register Using to reset registers
References registers.
Referenced by DMAC< BUSWIDTH >::mth_reset(), and DummySlave< BUSWIDTH >::mth_reset().
set_register_callback()
void set_register_callback (const std::string & name, Register::Callback cb) [inline]
update_register Using to register register callback function
Parameters
name The register name
cb The address of call back function
References registers.
Referenced by DMAC< BUSWIDTH >::init_registers(), and DummySlave< BUSWIDTH >::init_registers().
update_register()
void update_register (uint64_t address, uint32_t value) [inline]
update_register Using to update the value of register with specific address
Parameters
address The register address
Returns
value The new value that is wrote into this register
References registers.
Referenced by DMAC< BUSWIDTH >::nb_transport_fw(), and DummySlave< BUSWIDTH >::nb_transport_fw().
Member Data Documentation
registers
std::map<std::string, Register> registers [private]
Referenced by add_register(), dump_registers(), operator[](), operator[](), reset_regs(), set_register_callback(), and update_register().
The documentation for this class was generated from the following file:
common/ Registerif.h